-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 16:54:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hwdb03_대전_3_김정원
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hwdb03_대전_3_김정원
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hwdb03_대전_3_김정원` DEFAULT CHARACTER SET utf8 ;
USE `hwdb03_대전_3_김정원` ;

-- -----------------------------------------------------
-- Table `hwdb03_대전_3_김정원`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwdb03_대전_3_김정원`.`Customer` (
  `Customerid` INT NOT NULL,
  `cname` VARCHAR(45) NULL,
  `caddress` VARCHAR(45) NULL,
  `cphone1` VARCHAR(45) NULL,
  `cphone2` VARCHAR(45) NULL,
  PRIMARY KEY (`Customerid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwdb03_대전_3_김정원`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwdb03_대전_3_김정원`.`Product` (
  `idProduct` INT NOT NULL,
  `pname` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwdb03_대전_3_김정원`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwdb03_대전_3_김정원`.`Order` (
  `idOrder` INT NOT NULL,
  `OrderPrice` INT NULL,
  `ship` INT NULL,
  `pay` INT NULL,
  `Customer_Customerid` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_Customer1_idx` (`Customer_Customerid` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_Customerid`)
    REFERENCES `hwdb03_대전_3_김정원`.`Customer` (`Customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwdb03_대전_3_김정원`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwdb03_대전_3_김정원`.`OrderItem` (
  `idOrder` INT NOT NULL,
  `idProduct` INT NULL,
  `Order_idOrder` INT NULL,
  `Product_idProduct` INT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_OrderItem_Order_idx` (`Order_idOrder` ASC) VISIBLE,
  INDEX `fk_OrderItem_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_Order`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `hwdb03_대전_3_김정원`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `hwdb03_대전_3_김정원`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
